version: 2
jobs:
  bootstrap-build:
    docker:
      - image: codesmithy/gcc-bootstrap-build-prerequisites:0.2.0
    steps:
      - run: 
          name: "Set CODESMITHYIDE environment variables"
          command: echo 'export CODESMITHYIDE="/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /codesmithyide/version-control
      - run:
          name: Build
          command: cd /codesmithyide/version-control/git/build/gnumake && make
      - run:
          name: Test build
          command: cd /codesmithyide/version-control/git/Tests/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /codesmithyide/version-control/git/Tests/Makefiles/GNUmakefile && ./CodeSmithyGitTests
  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.1.0
    steps:
      - run:
          name: "Set CODESMITHYIDE environment variables"
          command: echo 'export CODESMITHYIDE="/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /codesmithyide/version-control
      - run:
          name: Build
          command: cd /codesmithyide/version-control/git/build/gnumake && make
      - run:
          name: Test build
          command: cd /codesmithyide/version-control/git/Tests/Makefiles/GNUmakefile && make
      - run:
          name: Run the tests
          command: cd /codesmithyide/version-control/git/Tests/Makefiles/GNUmakefile && ./CodeSmithyGitTests
workflows:
  version: 2
  build:
    jobs:
      - bootstrap-build
      - build
