version: 2
jobs:
  bootstrap-build:
    docker:
      - image: codesmithy/gcc-bootstrap-build-prerequisites:0.9.0
    steps:
      - run: 
          name: "Set CODESMITHYIDE_ROOT environment variables"
          command: echo 'export CODESMITHYIDE_ROOT="/workspace/projects/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/codesmithyide/version-control
      - run:
          name: Build
          command: cd /workspace/projects/codesmithyide/version-control/git/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/codesmithyide/version-control/git/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/codesmithyide/version-control/git/tests/build-files/gnumake && ./CodeSmithyGitTests
  build:
    docker:
      - image: codesmithy/gcc-build-prerequisites:0.13.0
    steps:
      - run:
          name: "Set CODESMITHYIDE_ROOT environment variables"
          command: echo 'export CODESMITHYIDE_ROOT="/workspace/projects/codesmithyide"' >> $BASH_ENV
      - checkout:
          path: /workspace/projects/codesmithyide/version-control
      - run:
          name: Build
          command: cd /workspace/projects/codesmithyide/version-control/git/build-files/gnumake && make
      - run:
          name: Test build
          command: cd /workspace/projects/codesmithyide/version-control/git/tests/build-files/gnumake && make
      - run:
          name: Run the tests
          command: cd /workspace/projects/codesmithyide/version-control/git/tests/build-files/gnumake && ./CodeSmithyGitTests
workflows:
  version: 2
  build:
    jobs:
      - bootstrap-build
      - build
  weekly_build:
    jobs:
      - bootstrap-build
      - build
    triggers:
      - schedule:
          cron: "0 8 * * 0"
          filters:
            branches:
              only:
                 - main
